ARG GO_VERSION=latest
ARG BASE_IMAGE=caracolazul/golang:${GO_VERSION}

FROM ${BASE_IMAGE}

WORKDIR /home/go

#
#  Dev (IDE) tools

RUN go install github.com/766b/go-outliner@latest
RUN go install golang.org/x/tools/gopls@latest
RUN go install honnef.co/go/tools/cmd/staticcheck@latest

# Prepare VS Code Server mount Point
RUN mkdir -p .vscode-server

ENTRYPOINT ["/bin/bash", "-c"]
CMD [ "while true; do sleep 1000; done" ]